name = "Hex Mod Pack"
author = "tjamesw123"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7bc123cd96bd1f6b04317aeec9f0ca69eaa56f781d111dc38c3c4965dfd1a1bf"

[versions]
fabric = "0.15.11"
minecraft = "1.19.2"
