name = "Hex Mod Pack"
author = "tjamesw123"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "aa5d29ae8246284359b0f4a48a6b7b50f8dfc7c6e441741ddce646f10d4725b8"

[versions]
fabric = "0.15.11"
minecraft = "1.19.2"
