name = "Hex Mod Pack"
author = "tjamesw123"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0956f184cd71d6b51740d7395b9cf69f1800b9bff8d5f9ca267027cd7406b339"

[versions]
fabric = "0.15.11"
minecraft = "1.19.2"
