name = "Hex Mod Pack"
author = "tjamesw123"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fbe6a28eb6a7a42d8216677ce52310f3fe31ac59961659da756e5c8daebe908a"

[versions]
fabric = "0.15.11"
minecraft = "1.19.2"
