name = "Hex Mod Pack"
author = "tjamesw123"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "83946b8f0beb2247d8481940114ae83ab8c21fd246b17008ef9afe38a66c297f"

[versions]
fabric = "0.15.11"
minecraft = "1.19.2"
