name = "Hex Mod Pack"
author = "tjamesw123"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a1f73c4323cc08e6b84d7e53f1916ff2b899c14d77fbb94ce0e35fbc10804543"

[versions]
fabric = "0.15.11"
minecraft = "1.19.2"
